<?php

use Illuminate\Database\Seeder;

class TeacherTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('teacher')->delete();
        
        \DB::table('teacher')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name_th' => 'ผศ.วิสูตร วรสง่าศิลป์',
                'name_en' => 'Asst.Prof.Wisoot Worasangasilp',
                'doctor_degree' => '',
            'master_degree' => 'M.Sc. (Computing and Information Science) Roosevelt University, USA (1988)',
            'bachelor_degree' => 'วศ.บ. (วิศวกรรมโยธา) มหาวิทยาลัยขอนแก่น (2524)',
                'email' => 'worasangasilp_w@su.ac.th',
                'website' => '',
                'position' => '',
                'expertise' => 'Database, Artificial Intelligence',
                'rank' => 20,
                'image' => 1,
                'token' => 'U1MHWB',
                'password' => '$2y$10$W4TBARCz1Dw0ZG4xlEooBOWpEEvmNMgeUKKenY4GKuLeLUTF9fkTe',
                'user_id' => 3,
                'created_at' => '2017-05-15 20:34:20',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            1 => 
            array (
                'id' => 2,
                'name_th' => 'อ.ดร.ทัศนวรรณ ศูนย์กลาง',
                'name_en' => 'Dr.Tasanawan Soonklang',
            'doctor_degree' => 'Ph.D. (Electronics and Electrical Engineering) University of Southampton, UK (2551)',
            'master_degree' => 'วท.ม. (วิทยาศาสตร์คอมพิวเตอร์) จุฬาลงกรณ์มหาวิทยาลัย (2544)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) เกียรตินิยมอันดับสอง มหาวิทยาลัยศิลปากร (2539)',
                'email' => 'soonklang_t@su.ac.th',
                'website' => 'http://www.cp.su.ac.th/~tasanawa',
                'position' => '',
                'expertise' => 'Natural Language Processing, Machine Learning',
                'rank' => 10,
                'image' => 2,
                'token' => 'MFswc7',
                'password' => '$2y$10$eOakQVDAPiRTlAlxyjy3JOKI8e3iXG62fXvAUttMHVJmSq4z9qZCq',
                'user_id' => 4,
                'created_at' => '2017-05-15 20:34:20',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            2 => 
            array (
                'id' => 3,
                'name_th' => 'อ.ดร.ภิญโญ แท้ประสาทสิทธิ์',
                'name_en' => 'Dr.Pinyo Taeprasartsit',
            'doctor_degree' => 'Ph.D. (Computer Science and Engineering) The Pennsylvania State University, USA (2554)',
            'master_degree' => 'M.Sc. (Computer Science and Engineering) The Pennsylvania State University, USA (2549)',
            'bachelor_degree' => 'วศ.บ. (วิศวกรรมคอมพิวเตอร์) เกียรตินิยมอันดับสอง จุฬาลงกรณ์มหาวิทยาลัย (2544)',
                'email' => 'pinyotae@gmail.com และ taeprasartsit_p@su.ac.th',
                'website' => 'http://www.cp.su.ac.th/~pinyotae/',
                'position' => '',
                'expertise' => 'Medical Image Processing, Computer Vision, Pattern Recognition, Machine Learning, High Performance Computing',
                'rank' => 10,
                'image' => 3,
                'token' => '7hsdaT',
                'password' => '$2y$10$csm9AYayEaf9p/26Pf550e9Y5zkLvmpTJkY.JWpLDd4pLLHoF9NAu',
                'user_id' => 5,
                'created_at' => '2017-05-15 20:34:20',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            3 => 
            array (
                'id' => 4,
                'name_th' => 'อ.ดร.กรัญญา สิทธิสงวน',
                'name_en' => 'Dr.Karanya Sitdhisanguan',
            'doctor_degree' => 'ปร.ด (เทคโนโลยีสารสนเทศ ) สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง (2555)',
            'master_degree' => 'M.Sc. (Applied Computer Science and Technology) Azusa Pacific University, USA (2541)',
            'bachelor_degree' => 'ศ.บ. (ออกแบบภายใน) มหาวิทยาลัยรังสิต (2536)',
                'email' => 'sitdhisanguan_k@su.ac.th',
                'website' => '',
                'position' => '',
                'expertise' => 'Augmented/Virtual Reality, Human Computer Interaction, Game Design and Development, Ubiquitous Computing',
                'rank' => 10,
                'image' => 4,
                'token' => 'WoPaal',
                'password' => '$2y$10$kOgfZErYbv9Gy4L6zj11HOOhVUXJi8tKbpJDjm56gXd2DG8vo8jtO',
                'user_id' => 6,
                'created_at' => '2017-05-15 20:34:20',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            4 => 
            array (
                'id' => 5,
                'name_th' => 'ผศ.ดร.คทา ประดิษฐวงศ์',
                'name_en' => 'Dr.Kata Praditwong',
            'doctor_degree' => 'Ph.D. (Computer Science) University of Birmingham, UK (2551)',
            'master_degree' => 'วท.ม. (วิทยาศาสตร์คอมพิวเตอร์) จุฬาลงกรณ์มหาวิทยาลัย (2544)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) เกียรตินิยมอันดับสอง มหาวิทยาลัยศิลปากร (2539)',
                'email' => 'praditwong_k@su.ac.th',
                'website' => '',
                'position' => '',
                'expertise' => 'Evolutionary Algorithms, Metaheuristics, Optimization',
                'rank' => 25,
                'image' => 5,
                'token' => '5fHfDV',
                'password' => '$2y$10$1xhQu5xtPChL0u.UMVfGj.CMMoYqIDsdvLcm2lzvC6rACX3sQTr6y',
                'user_id' => 7,
                'created_at' => '2017-05-15 20:34:20',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            5 => 
            array (
                'id' => 6,
                'name_th' => 'ผศ.บัณฑิต ภูริชิติพร',
                'name_en' => 'Asst.Prof.Bandid Bhurichitiporn',
                'doctor_degree' => '',
            'master_degree' => 'พบ.ม. (สถิติประยุกต์) สาขาคอมพิวเตอร์ สถาบันบัณฑิตพัฒนบริหารศาสตร์ (2533)',
            'bachelor_degree' => 'วท.บ. (คณิตศาสตร์) มหาวิทยาลัยศิลปากร (2528)',
                'email' => 'bhurichitiporn_b@su.ac.th',
                'website' => '',
                'position' => '',
                'expertise' => 'Discrete Computational Structure, Mathematics',
                'rank' => 20,
                'image' => 6,
                'token' => '8daDJL',
                'password' => '$2y$10$0Sf21.T1Hms7rXgPxykicOkWiY0/Qb1dDAEV4t4Uhe1TYnLbME/si',
                'user_id' => 8,
                'created_at' => '2017-05-15 20:34:20',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            6 => 
            array (
                'id' => 7,
                'name_th' => 'รศ.ดร.ปานใจ ธารทัศนวงศ์',
                'name_en' => 'Assoc.Prof.Dr.Panjai Tantatsanawong',
            'doctor_degree' => 'Ph.D. (Computer Science) Asian Institute of Technology, Thailand (2000)',
            'master_degree' => 'วท.ม. (วิทยาศาสตร์คอมพิวเตอร์) จุฬาลงกรณ์มหาวิทยาลัย (2535)',
            'bachelor_degree' => 'วท.บ. (สาธารณสุขศาสตร์) มหาวิทยาลัยมหิดล (2527)',
                'email' => 'tantatsanawong_p@su.ac.th',
                'website' => '',
                'position' => '',
                'expertise' => 'Software Engineering, Computer Networks',
                'rank' => 35,
                'image' => 7,
                'token' => 'cTXjHZ',
                'password' => '$2y$10$elhDJaZY4VjfNvfJiJnlLeV.zLcXxl0Gc9khx./JaqVmHbrUnv03m',
                'user_id' => 9,
                'created_at' => '2017-05-15 20:34:20',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            7 => 
            array (
                'id' => 8,
                'name_th' => 'อ.ดร.รัชดาพร คณาวงษ์',
                'name_en' => 'Dr.Ratchadaporn Kanawong',
            'doctor_degree' => 'Ph.D. (Computer Science) University of Missouri-Columbia, USA (2012)',
            'master_degree' => 'วศ.ม. (วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าเจ้าธนบุรี (2545)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) มหาวิทยาลัยศิลปากร (2539)',
                'email' => 'kanawong_r@su.ac.th',
                'website' => 'http://www.cp.su.ac.th/~kanawong',
                'position' => '',
                'expertise' => 'Image Processing, Computer Vision, Machine Learning',
                'rank' => 10,
                'image' => 8,
                'token' => 'NqhN59',
                'password' => '$2y$10$KHIr.jByhVJK0SWWMSIJIepHgZlEfEsDyiBlLppC44Zuyzmgl2CWa',
                'user_id' => 10,
                'created_at' => '2017-05-15 20:34:20',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            8 => 
            array (
                'id' => 9,
                'name_th' => 'ผศ.สุจิตรา อดุลย์เกษม',
                'name_en' => 'Asst.Prof.Suchitra Adulkasem',
                'doctor_degree' => '',
            'master_degree' => 'M.Sc. (Computer Science) Asian Institute of Technology, Thailand (2535)',
            'bachelor_degree' => 'ศษ.บ. (คณิตศาสตร์) มหาวิทยาลัยเชียงใหม่ (2526)',
                'email' => 'adulkasem_s@su.ac.th',
                'website' => '',
                'position' => '',
                'expertise' => 'Access Control and Security, Database Application and Information Technology, Medical Image and Information Processing',
                'rank' => 20,
                'image' => 9,
                'token' => 'Oibfoa',
                'password' => '$2y$10$ay6jRbUzwnklvlIb7Zw3CefcFFvO9Dzl7aEEqDuCRx7zSEISb4r9a',
                'user_id' => 11,
                'created_at' => '2017-05-15 20:34:20',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            9 => 
            array (
                'id' => 10,
                'name_th' => 'อ.ดร.สุนีย์ พงษ์พินิจภิญโญ',
                'name_en' => 'Dr.Sunee Pongpinigpinyo',
            'doctor_degree' => 'วศ.ด. (วิศวกรรมคอมพิวเตอร์) จุฬาลงกรณ์มหาวิทยาลัย (2549)',
            'master_degree' => 'M.Sc. (Computer Science) Tasmania University, Australia (2539)',
            'bachelor_degree' => 'วท.บ. (สถิติ) เกียรตินิยมอันดับสอง มหาวิทยาลัยศิลปากร (2530)',
                'email' => 'pongpinigpinyo_s@su.ac.th',
                'website' => '',
                'position' => '',
                'expertise' => 'Data Mining, Machine Learning, Distributed Database, Data Warehouse, Decision Support System, Knowledge Engineering',
                'rank' => 10,
                'image' => 10,
                'token' => '3ouqrx',
                'password' => '$2y$10$IC7Kvs4qCeU94LSolgeR9uB3hxT4E.MFVraR65PnyhII88uiAQN1.',
                'user_id' => 12,
                'created_at' => '2017-05-15 20:34:21',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            10 => 
            array (
                'id' => 11,
                'name_th' => 'อ.ดร.วีณาวดี ม่วงอ้น',
                'name_en' => 'Dr.Weenawadee Muangon',
            'doctor_degree' => 'ปร.ด.(วิทยาการคอมพิวเตอร์) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง (2556)',
            'master_degree' => 'วท.ม. (วิทยาการคอมพิวเตอร์) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง (2549)',
            'bachelor_degree' => 'วท.บ. (คณิตศาสตร์ประยุกต์) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง (2544)',
                'email' => 'muangon_w@su.ac.th',
                'website' => '',
                'position' => '',
                'expertise' => 'Case-Base Reasoning for Design Patterns Retrieval, Case-Base Reasoning, Information Retrieval, Software Engineering',
                'rank' => 10,
                'image' => 11,
                'token' => 'peamTf',
                'password' => '$2y$10$mdBVjkNmmL6Z/o.c8uF8JOJIDn.r.nJuNqMtOxuMmYBi4bO.wTq4a',
                'user_id' => 13,
                'created_at' => '2017-05-15 20:34:21',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            11 => 
            array (
                'id' => 12,
                'name_th' => 'อ.ดร.วัสรา รอดเหตุภัย',
                'name_en' => 'Dr.Wasara Rodhetbhai',
            'doctor_degree' => 'Ph.D. (Computer Science) University of Southampton, UK (2552)',
            'master_degree' => 'วศ.ม. (วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเกษตรศาสตร์ (2545)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) เกียรตินิยมอันดับสอง มหาวิทยาลัยศิลปากร (2539)',
                'email' => 'wasara@cp.su.ac.th',
                'website' => '',
                'position' => '',
                'expertise' => 'Multimedia Retrieval, Web/Internet Technology, Distributed Systems',
                'rank' => 10,
                'image' => 12,
                'token' => 'G45WGR',
                'password' => '$2y$10$bKRdrvwqbELO1xB0ietVC.a8k1bJnvRTWxibz770SNDGsshk7EG8.',
                'user_id' => 14,
                'created_at' => '2017-05-15 20:34:21',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            12 => 
            array (
                'id' => 13,
                'name_th' => 'อ.เสฐลัทธ์ รอดเหตุภัย',
                'name_en' => 'Sethalat Rodhetbhai',
                'doctor_degree' => '',
            'master_degree' => 'วศ.ม. (วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเกษตรศาสตร์ (2545)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) เกียรตินิยมอันดับสอง มหาวิทยาลัยศิลปากร (2537)',
                'email' => 'sethalat@cp.su.ac.th',
                'website' => 'http://www.cp.su.ac.th/~sethalat',
                'position' => '',
                'expertise' => 'Computer Networks, Distributed Systems, Ubiquitous and Mobile Computing',
                'rank' => 5,
                'image' => 13,
                'token' => 'zrxx4w',
                'password' => '$2y$10$wMrbS.eSRrB6ELxOyAcMBev4H0E14Kv/13pEjnfg.pqzFYYLgqD4K',
                'user_id' => 15,
                'created_at' => '2017-05-15 20:34:21',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            13 => 
            array (
                'id' => 14,
                'name_th' => 'อ.ดร.เสาวลักษณ์ อร่ามพงศานุวัต',
                'name_en' => 'Dr.Saowalak Arampongsanuwat',
            'doctor_degree' => 'ปร.ด. (เทคโนโลยีสารสนเทศ) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ (2557)',
            'master_degree' => 'วท.ม. (เทคโนโลยีสารสนเทศ) สถาบันเทคโนโลยีพระจอมเกล้าพระนครเหนือ (2546)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) มหาวิทยาลัยศิลปากร (2544)',
                'email' => 'arampongsanuwat_s@su.ac.th',
                'website' => 'http://www.cp.su.ac.th/~saowalak',
                'position' => '',
                'expertise' => 'Artificial Intelligence, Data Mining, Business Intelligence',
                'rank' => 10,
                'image' => 14,
                'token' => 'tAbW5g',
                'password' => '$2y$10$kdD8tcL937pNXuFYXCG04eInLuNHEgeqIbjc04pyoy7Y0xJ.Zk1Zm',
                'user_id' => 16,
                'created_at' => '2017-05-15 20:34:21',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            14 => 
            array (
                'id' => 15,
                'name_th' => 'อ.ดร.อรวรรณ เชาวลิต',
                'name_en' => 'Dr.Orawan Chaowalit',
            'doctor_degree' => 'Ph.D. (Computer Science) National Institute of Development Administration, Thailand (2557)',
            'master_degree' => 'วท.ม. (วิทยาการคอมพิวเตอร์) มหาวิทยาลัยธรรมศาสตร์ (2547)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) มหาวิทยาลัยศิลปากร (2539)',
                'email' => 'chaowalit_o@su.ac.th',
                'website' => 'http://www.cp.su.ac.th/~orawan/',
                'position' => '',
                'expertise' => 'Database Application and Design, Data Warehouse and Application, Enterprise Application Programing and Design, System Analysis and Design',
                'rank' => 10,
                'image' => 15,
                'token' => 'ZUBTbE',
                'password' => '$2y$10$K74ht0lRfxE0yw1mlSO9wO9gPGIYLuXi.JjkyRB6/grn6LLY4n63u',
                'user_id' => 17,
                'created_at' => '2017-05-15 20:34:21',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            15 => 
            array (
                'id' => 16,
                'name_th' => 'อ.โอภาส วงษ์ทวีทรัพย์',
                'name_en' => 'Opas Wongtaweesap',
                'doctor_degree' => '',
            'master_degree' => 'วท.ม. (วิทยาศาสตร์คอมพิวเตอร์) จุฬาลงกรณ์มหาวิทยาลัย (2550)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) เกียรตินิยมอันดับสอง มหาวิทยาลัยศิลปากร (2546)',
                'email' => 'oatcomster@gmail.com',
                'website' => 'http://web.sc.su.ac.th/oatcom, http://twitter.com/OaTCoM',
                'position' => '',
                'expertise' => 'Knowledge and Information Engineering, Data Mining, KM, Visualization, Pattern Recognition, NLP, Cognitive, Emotional Analysis and Behaviour',
                'rank' => 5,
                'image' => 16,
                'token' => 'CLdQVu',
                'password' => '$2y$10$Vmrmqij2yzkUGoZrlMEqeutL4iBrdd1CQbjw4h9Uw8yIpckabX9Ry',
                'user_id' => 18,
                'created_at' => '2017-05-15 20:34:21',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            16 => 
            array (
                'id' => 17,
                'name_th' => 'อ.อภิเษก หงษ์วิทยากร',
                'name_en' => 'Apisake Hongwitayakorn',
                'doctor_degree' => '',
            'master_degree' => 'M.EngSci. (Computer Engineering) University of Adelaide, Australia (2546)',
            'bachelor_degree' => 'วศ.บ. (คอมพิวเตอร์) มหาวิทยาลัยสงขลานครินทร์ (2536)',
                'email' => 'hongwitayakorn_a@cp.su.ac.th',
                'website' => 'http://www.cp.su.ac.th/~apisake',
                'position' => 'รองหัวหน้าภาควิชา',
                'expertise' => 'Digital System Design, Memory Architecture, Embedded System, Microarchitecture Design Techniques',
                'rank' => 50,
                'image' => 17,
                'token' => 'zaz0ja',
                'password' => '$2y$10$QVKLSwV7z5UKGqLld6nR5uycd9sISZQlSmlk8BbjF0CpkF95kxMx2',
                'user_id' => 19,
                'created_at' => '2017-05-15 20:34:21',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            17 => 
            array (
                'id' => 18,
                'name_th' => 'อ.ดร.กฤษณะ สีพนมวัน',
                'name_en' => 'Dr.Kristsana Seepanomwan',
            'doctor_degree' => 'Ph.D. (Computing) Plymouth University, UK (2559)',
            'master_degree' => 'วท.ม. (วิทยาการคอมพิวเตอร์) สถาบันเทคโนโลยีพระจอมเกล้าพระนครเหนือ (2550)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) สถาบันราชภัฏนครปฐม (2542)',
                'email' => 'seepanomwan_k@su.ac.th',
                'website' => 'http://www.cp.su.ac.th/~kns',
                'position' => '',
                'expertise' => 'Robotics, Wireless Communication',
                'rank' => 10,
                'image' => 18,
                'token' => 'WgGVfo',
                'password' => '$2y$10$Dslo4QodvvFihmIY5YGHL.5uDzKJJbbN9176Xtpx8JnbpOWtT1XIO',
                'user_id' => 20,
                'created_at' => '2017-05-15 20:34:21',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            18 => 
            array (
                'id' => 19,
                'name_th' => 'อ.ดร.ณัฐโชติ พรหมฤทธิ์',
                'name_en' => 'Dr.Nuttachot Promrit',
            'doctor_degree' => 'ปร.ด. (เทคโนโลยีสารสนเทศ) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ (2558)',
            'master_degree' => 'วท.ม. (เทคโนโลยีสารสนเทศ) สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง (2548)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) มหาวิทยาลัยทักษิณ (2542)',
                'email' => 'promrit_n@su.ac.th',
                'website' => 'http://www.cp.su.ac.th/~npromrit',
                'position' => 'หัวหน้าภาควิชา',
                'expertise' => 'Network Management, Computer and Network Security',
                'rank' => 100,
                'image' => 19,
                'token' => 'EnscW9',
                'password' => '$2y$10$ybUhhg6cpSPnFoqmwzu7b.gKrd1wGV6hwq5YEJIcxomOfMFBpv3MS',
                'user_id' => 21,
                'created_at' => '2017-05-15 20:34:22',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            19 => 
            array (
                'id' => 20,
                'name_th' => 'อ.ดร.สิรักข์ แก้วจำนงค์',
                'name_en' => 'Dr.Sirak Kaewjamnong',
            'doctor_degree' => 'Ph.D. (Computer Science) Lancaster University, UK (2015)',
            'master_degree' => 'วศ.ม. (วิศวกรรมคอมพิวเตอร์) มหาวิทยาลัยเกษตรศาสตร์ (2544)',
            'bachelor_degree' => 'วท.บ. (วิทยาการคอมพิวเตอร์) สถาบันเทคโนโลยีราชมงคล (2540)',
                'email' => 'kaewjamnong_s@su.ac.th',
                'website' => 'http:/www.cp.su.ac.th/~sirak',
                'position' => '',
                'expertise' => 'Computer Network Architectures, Algorithms and Protocols',
                'rank' => 10,
                'image' => 20,
                'token' => 'ki14iy',
                'password' => '$2y$10$GBe9XWFkYT7fCm1B5beXmOtlrYUakWvRQmHSHnx7GweUM/dTYDPnC',
                'user_id' => 22,
                'created_at' => '2017-05-15 20:34:22',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
            20 => 
            array (
                'id' => 21,
                'name_th' => 'อ.ดร.สัจจาภรณ์ ไวจรรยา',
                'name_en' => 'Dr.Sajjaporn Waijanya',
            'doctor_degree' => 'ปร.ด. (เทคโนโลยีสารสนเทศ) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ (2557)',
            'master_degree' => 'วท.ม. (วิทยาศาสตร์คอมพิวเตอร์) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ (2550)',
            'bachelor_degree' => 'วท.บ. (เทคโนโลยีสารสนเทศ) มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี (2541)',
                'email' => 'sajjaporn.w@gmail.com',
                'website' => NULL,
                'position' => NULL,
                'expertise' => 'Software Engineering, Natural Language Processing, Web Programming / Technology',
                'rank' => 10,
                'image' => 21,
                'token' => 'XkrrW3',
                'password' => '$2y$10$7uV3wgluCDnlTa9Tm3QKa.BwbGQFVqa7O9U4HsTovqUMwSwaoBlou',
                'user_id' => 23,
                'created_at' => '2017-05-15 20:34:22',
                'updated_at' => '2017-08-22 23:23:27',
                'status' => 'duty',
            ),
        ));
        
        
    }
}